name: coffea
channels:
  - anaconda
  - conda-forge
dependencies:
  - ipython
  - uproot
  - xxhash
  - xrootd
  - pandas
  - tqdm
  - cloudpickle
  - lz4
  - six
  - matplotlib>=3
  - numba>=0.43.1
  - numpy>=1.16.0
  - scipy>=1.1.0
  - pip
  - pip:
      - https://github.com/CoffeaTeam/coffea/archive/344a2949eac5d603ab7223823d31ca7fe61111a1.zip
